import { createHash } from 'node:crypto';
import { readdir } from 'node:fs/promises';
import { basename, join } from 'node:path';

const STRUCTURE_HASH_RE = /\n<!--\s*structure-hash:\s*([a-f0-9]+)\s*-->\s*$/i;
const STRUCTURE_STATUS_RE = /\n<!--\s*structure-status:\s*(deterministic|enriched)\s*-->\s*/i;
const STRUCTURE_SKIP_DIRS = new Set([
  '.git',
  '.moon',
  '.turbo',
  'coverage',
  'dist',
  'node_modules',
]);

export type StructurePackageInfo = {
  readonly name: string;
  readonly rel: string;
  readonly description: string;
  readonly subpaths?: Readonly<Record<string, string>>;
};

export async function walkStructureTree(
  dir: string,
  prefix = '',
  depth = 0,
  maxDepth = 3,
): Promise<string[]> {
  if (depth > maxDepth) return [];

  let items: string[];
  try {
    items = await readdir(dir);
  } catch {
    return [];
  }

  const lines: string[] = [];
  for (const item of items.filter((name) => !STRUCTURE_SKIP_DIRS.has(name)).sort()) {
    lines.push(`${prefix}${item}`);
    lines.push(...(await walkStructureTree(join(dir, item), `${prefix}  `, depth + 1, maxDepth)));
  }

  return lines;
}

export function computeStructureTreeHash(entries: readonly string[]): string {
  return createHash('sha256')
    .update([...entries].sort().join('\n'))
    .digest('hex');
}

export function readEmbeddedStructureHash(content: string): string | null {
  return content.match(STRUCTURE_HASH_RE)?.[1] ?? null;
}

export function structureNeedsEnrichment(content: string): boolean {
  return /<!--\s*structure-status:\s*deterministic\s*-->/.test(content);
}

export function stripStructureMetadata(content: string): string {
  return content.replace(STRUCTURE_STATUS_RE, '').replace(STRUCTURE_HASH_RE, '').trimEnd();
}

export function embedStructureMetadata(
  content: string,
  hash: string,
  opts: { needsEnrichment?: boolean } = {},
): string {
  const stripped = stripStructureMetadata(content);
  const status = opts.needsEnrichment ? 'deterministic' : 'enriched';
  return `${stripped}\n\n<!-- structure-status: ${status} -->\n<!-- structure-hash: ${hash} -->\n`;
}

export function renderStructureSkeleton(
  pkg: StructurePackageInfo,
  treeLines: readonly string[],
): string {
  const treeBlock = treeLines.length > 0 ? treeLines.join('\n') : '(empty package tree)';
  const exportLines = renderExportLines(pkg);

  return [
    `# \`${pkg.name}\` — Structure`,
    '',
    pkg.description || 'Deterministic package structure map generated from the checked-in tree.',
    '',
    `Workspace path: \`${pkg.rel}\``,
    '',
    '## Directory Tree',
    '',
    '```text',
    treeBlock,
    '```',
    '',
    '## Public Entry Points',
    '',
    exportLines,
    '',
    '## Documentation Contract',
    '',
    '- README.md',
    '- API.md',
    '- STRUCTURE.md',
    '',
    '> Regenerated by `pnpm gen:structure`. Optional prose enrichment may be applied afterwards.',
  ].join('\n');
}

function renderExportLines(pkg: StructurePackageInfo): string {
  const subpaths = Object.entries(pkg.subpaths ?? {}).filter(([subpath]) => subpath !== './package.json');
  if (subpaths.length === 0) {
    return '- No package.json exports map was detected.';
  }

  return subpaths
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([subpath, dtsPath]) => {
      const importTarget = subpath === '.' ? pkg.name : `${pkg.name}${subpath.slice(1)}`;
      return `- \`${importTarget}\` → \`${dtsPath}\``;
    })
    .join('\n');
}

export function detectLegacyStructureAlias(content: string): string | null {
  const heading = content.split('\n', 1)[0] ?? '';
  const match = heading.match(/^#\s+`?(framework|platform|domains)\/([^`\s]+)`?/i);
  if (!match) return null;
  return `${match[1]}/${match[2]}`;
}

export function structureIdentityTokens(pkg: Pick<StructurePackageInfo, 'name' | 'rel'>): string[] {
  return [pkg.name, pkg.rel, basename(pkg.rel)];
}