packages:
  - "repos/cfx-config/packages/*"
  - "repos/cfx-meta/packages/*"
  - "repos/*/packages/*"
  - "repos/cfx-tools/devtools/*"
  - "repos/cfx-tools/infra/*"
  - "repos/cfx-tools/templates/*"
  - "projects/*/apps/*"
  - "projects/*/packages/*"
  - "projects/*/contracts"
