packages:
  - "tools/*"
  - "tools/codegen/contracts-extract"
  - "framework/*"
  - "domains/*"
  - "platform/*"
  - "platform/templates/*"
  - "platform/devtools/*"
  - "projects/*/apps/*"
  - "projects/*/packages/*"
  - "projects/*/contracts"
