import fs from 'node:fs/promises';
import path from 'node:path';

import { findRepoRoot, getDocsSitePaths } from './workspace.js';

const SKIP_PACKAGES = new Set([
  '@cfxdevkit/biome-config',
  '@cfxdevkit/tsconfig',
  '@cfxdevkit/moon-config',
  '@cfxdevkit/arch-rules',
  '@cfxdevkit/docs-site',
]);

const REPO_DIRS = [
  { dir: 'repos/cfx-core', tier: 0, slice: 'cfx-core' },
  { dir: 'repos/cfx-keys', tier: 0, slice: 'cfx-keys' },
  { dir: 'repos/cfx-ui', tier: 0, slice: 'cfx-ui' },
  { dir: 'repos/cfx-solidity', tier: 0, slice: 'cfx-solidity' },
  { dir: 'repos/cfx-tools', tier: 1, slice: 'cfx-tools' },
  { dir: 'repos/cfx-domain', tier: 2, slice: 'cfx-domain' },
] as const;

type ArchitecturePackage = {
  name: string;
  tier: number;
  slice: string;
};

async function discoverArchitecturePackages(repoRoot: string): Promise<ArchitecturePackage[]> {
  const result: ArchitecturePackage[] = [];
  for (const { dir, tier, slice } of REPO_DIRS) {
    for (const parent of ['packages', 'infra']) {
      const parentDir = path.join(repoRoot, dir, parent);
      let entries: string[];
      try {
        entries = await fs.readdir(parentDir);
      } catch {
        continue;
      }
      for (const entry of entries) {
        const pkgPath = path.join(parentDir, entry, 'package.json');
        let pkgJson: { name?: string; private?: boolean } | null = null;
        try {
          pkgJson = JSON.parse(await fs.readFile(pkgPath, 'utf8')) as {
            name?: string;
            private?: boolean;
          };
        } catch {
          continue;
        }
        if (!pkgJson?.name || pkgJson.private === true) continue;
        if (SKIP_PACKAGES.has(pkgJson.name)) continue;
        result.push({ name: pkgJson.name, tier, slice });
      }
    }
  }
  return result;
}

function buildPackageMapTable(packages: ArchitecturePackage[]): string {
  const rows = packages
    .sort((left, right) => left.tier - right.tier || left.name.localeCompare(right.name))
    .map((pkg) => `| \`${pkg.name}\` | ${pkg.tier} | \`repos/${pkg.slice}\` |`);
  return `| Package | Tier | Repo slice |
|---|---|---|
${rows.join('\n')}`;
}

function boxLine(text: string): string {
  const body = text.length > 64 ? `${text.slice(0, 61)}...` : text.padEnd(64);
  return `│  ${body}│`;
}

export async function syncArchitecturePage(): Promise<number> {
  const repoRoot = findRepoRoot();
  const { contentDir } = getDocsSitePaths(repoRoot);
  const dest = path.join(contentDir, 'architecture.mdx');

  const packages = await discoverArchitecturePackages(repoRoot);
  const packageMapTable = buildPackageMapTable(packages);
  const tier0 = [...new Set(packages.filter((pkg) => pkg.tier === 0).map((pkg) => pkg.slice))];
  const tier1 = [...new Set(packages.filter((pkg) => pkg.tier === 1).map((pkg) => pkg.slice))];
  const tier2 = [...new Set(packages.filter((pkg) => pkg.tier === 2).map((pkg) => pkg.slice))];

  const mdx = `---
title: Architecture
description: Layered architecture and dependency rules for the cfxdevkit monorepo.
---

import { Callout } from 'nextra/components'

# Architecture

cfxdevkit follows a **four-tier layered architecture**. Dependencies flow downward only — no upward or circular imports are allowed.

## Tier model

\`\`\`
┌──────────────────────────────────────────────────────────────────┐
│  Tier 3 — Projects & Apps                                        │
${boxLine('projects/cas  │  projects/chainbrawler  │  projects/electro')}
├──────────────────────────────────────────────────────────────────┤
│  Tier 2 — Domain Logic                                           │
${boxLine(tier2.map((slice) => `repos/${slice}`).join(' │ '))}
├──────────────────────────────────────────────────────────────────┤
│  Tier 1 — Developer Platform                                     │
${boxLine(tier1.map((slice) => `repos/${slice}`).join(' │ '))}
├──────────────────────────────────────────────────────────────────┤
│  Tier 0 — Framework                                              │
${boxLine(tier0.join(' │ '))}
└──────────────────────────────────────────────────────────────────┘
             ▲             ▲             ▲
        tools/       infrastructure/   docs/   ← cross-cutting
\`\`\`

## Package map

${packageMapTable}

## Key principles

**One-way dependency graph** — Tiers cannot create cycles. A tier-0 package must never import from tier-1 or higher.

**Explicit public surfaces** — Every publishable package exposes an \`exports\` map in \`package.json\`. Deep imports outside the declared sub-paths are not supported.

**No circular dependencies** — Enforced by Moon task ordering and \`arch-check\` CI gate.

**Config packages are not tiers** — Shared config packages (\`biome-config\`, \`tsconfig\`, \`moon-config\`, \`arch-rules\`) are build-time utilities excluded from the tier model.

<Callout type="info">
  This file is fully regenerated by \`pnpm sync:architecture\`. Do not edit manually.
</Callout>
`;

  await fs.writeFile(dest, mdx, 'utf8');
  console.log(`sync-architecture: wrote content/architecture.mdx (${packages.length} packages)`);
  return packages.length;
}
