import type { ScriptRequirement } from '../workspace.js';

export const rootLlmScriptRequirements: readonly ScriptRequirement[] = [
  {
    name: 'llm',
    expected: 'pnpm run agent',
    severity: 'warning',
    description: 'llm namespace compatibility shim',
  },
  {
    name: 'llm:all',
    expected: 'pnpm run cdk -- agent exploratory all',
    severity: 'warning',
    description: 'llm all alias',
  },
  {
    name: 'llm:actions',
    expected: 'pnpm run cdk -- agent exploratory actions',
    severity: 'warning',
    description: 'llm actions alias',
  },
  {
    name: 'llm:action',
    expected: 'pnpm run cdk -- agent exploratory action',
    severity: 'warning',
    description: 'llm action alias',
  },
  {
    name: 'llm:ask',
    expected: 'pnpm run cdk -- agent print --',
    severity: 'warning',
    description: 'llm ask alias',
  },
  {
    name: 'llm:changeset',
    expected: 'pnpm run cdk -- agent exploratory changeset',
    severity: 'warning',
    description: 'llm changeset alias',
  },
  {
    name: 'llm:ci-cd',
    expected: 'pnpm run cdk -- agent exploratory ci-cd',
    severity: 'warning',
    description: 'llm ci-cd alias',
  },
  {
    name: 'llm:config',
    expected: 'pnpm run cdk -- agent config',
    severity: 'warning',
    description: 'llm config alias',
  },
  {
    name: 'llm:commit',
    expected: 'pnpm run repo:commit',
    severity: 'warning',
    description: 'llm commit alias',
  },
  {
    name: 'llm:docs-api',
    expected: 'pnpm run cdk -- agent deterministic docs-api',
    severity: 'warning',
    description: 'docs API enrichment alias',
  },
  {
    name: 'llm:readme-upkeep',
    expected: 'pnpm run cdk -- agent deterministic readme-upkeep',
    severity: 'warning',
    description: 'README enrichment alias',
  },
  {
    name: 'llm:package-pages',
    expected: 'pnpm run cdk -- agent deterministic package-pages',
    severity: 'warning',
    description: 'package page enrichment alias',
  },
  {
    name: 'llm:structure-upkeep',
    expected: 'pnpm run cdk -- agent deterministic structure-upkeep',
    severity: 'warning',
    description: 'STRUCTURE upkeep alias',
  },
  {
    name: 'llm:wiki',
    expected: 'pnpm run docs:wiki',
    severity: 'warning',
    description: 'deprecated wiki alias routed through docs namespace',
  },
  {
    name: 'llm:docs-pipeline',
    expected: 'pnpm run cdk -- agent exploratory docs-pipeline',
    severity: 'warning',
    description: 'docs pipeline review alias',
  },
  {
    name: 'llm:docs-upkeep',
    expected: 'pnpm run cdk -- agent deterministic docs-upkeep',
    severity: 'warning',
    description: 'docs content upkeep alias',
  },
  {
    name: 'llm:health',
    expected: 'pnpm run cdk -- agent exploratory health',
    severity: 'warning',
    description: 'provider health alias',
  },
  {
    name: 'llm:models',
    expected: 'pnpm run cdk -- agent deterministic models',
    severity: 'warning',
    description: 'model discovery alias',
  },
  {
    name: 'llm:validate-models',
    expected: 'pnpm run cdk -- agent deterministic validate-models',
    severity: 'warning',
    description: 'model validation alias',
  },
  {
    name: 'llm:model',
    expected: 'pnpm run cdk -- agent config set default-model',
    severity: 'warning',
    description: 'interactive default-model alias',
  },
  {
    name: 'llm:release',
    expected: 'pnpm run cdk -- agent exploratory release',
    severity: 'warning',
    description: 'release helper alias',
  },
  {
    name: 'llm:review',
    expected: 'pnpm run repo:review',
    severity: 'warning',
    description: 'review alias',
  },
  {
    name: 'llm:test-audit',
    expected: 'pnpm run cdk -- agent exploratory test-audit',
    severity: 'warning',
    description: 'test audit alias',
  },
  {
    name: 'llm:test-upkeep',
    expected: 'pnpm run cdk -- agent exploratory test-upkeep',
    severity: 'warning',
    description: 'test upkeep alias',
  },
  {
    name: 'llm:validation',
    expected: 'pnpm run cdk -- agent exploratory validation',
    severity: 'warning',
    description: 'validation alias',
  },
];
