import { existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
import { confirm } from '@inquirer/prompts';
import type { WizardState } from '../wizard.js';

// Resolve from the CAS project root regardless of cwd.
// Built file lives at  projects/cas/packages/setup/dist/<chunk>.js
// so  ../../../  == projects/cas/
const CAS_ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../..');

function resolveFromCasRoot(rel: string): string {
  return join(CAS_ROOT, rel);
}

export function generateBackendEnv(state: WizardState): string {
  const lines: string[] = [
    '# Generated by cas-setup wizard',
    '',
    '# ── Server ───────────────────────────────────────────────────────────────────',
    'PORT=3011',
    'CAS_BACKEND_HOST=0.0.0.0',
    '',
    '# ── SQLite ────────────────────────────────────────────────────────────────────',
    '# CAS_SQLITE_PATH=../../.data/cas-dev.sqlite',
    '',
    '# ── Auth ──────────────────────────────────────────────────────────────────────',
    'CAS_AUTH_SECRET=cas-local-dev-secret',
    '',
    '# ── CORS ──────────────────────────────────────────────────────────────────────',
    '# CAS_CORS_ORIGINS=http://localhost:3010',
    '',
    '# ── Network ───────────────────────────────────────────────────────────────────',
    `NETWORK=${state.network === 'local' ? 'mainnet' : state.network}`,
    `CONFLUX_ESPACE_RPC=${state.rpcUrl}`,
    '',
    '# ── Contracts ─────────────────────────────────────────────────────────────────',
    `AUTOMATION_MANAGER_ADDRESS=${state.automationManagerAddress}`,
    `PRICE_ADAPTER_ADDRESS=${state.priceAdapterAddress}`,
    `PERMIT_HANDLER_ADDRESS=${state.permitHandlerAddress}`,
    `SWAPPI_ROUTER_ADDRESS=${state.swappiRouterAddress}`,
    '',
    '# ── Admin ─────────────────────────────────────────────────────────────────────',
    state.adminAddresses
      ? `ADMIN_ADDRESSES=${state.adminAddresses}`
      : '# ADMIN_ADDRESSES=0xYourAdminAddress',
    '',
    '# ── Keeper ────────────────────────────────────────────────────────────────────',
    `KEEPER_ENABLED=${state.keeperEnabled}`,
  ];

  if (state.keeperEnabled && state.signerKey) {
    lines.push(`SIGNER_PRIVATE_KEY=${state.signerKey}`);
  } else {
    lines.push('# WARNING: Never commit a real private key.');
    lines.push('# SIGNER_PRIVATE_KEY=0xYOUR_SIGNER_PRIVATE_KEY_HERE');
  }

  lines.push('# KEEPER_INTERVAL_MS=15000');
  lines.push('# KEEPER_CONCURRENCY=1');
  lines.push('# MAX_GAS_PRICE_GWEI=500');
  lines.push('');

  return lines.join('\n');
}

export function generateFrontendEnv(state: WizardState): string {
  const network = state.network === 'local' ? 'local' : state.network;
  const lines: string[] = [
    '# Generated by cas-setup wizard',
    '',
    '# ── CAS Backend ───────────────────────────────────────────────────────────────',
    'NEXT_PUBLIC_CAS_API_URL=http://127.0.0.1:3011',
    '',
    '# ── Network ───────────────────────────────────────────────────────────────────',
    `NEXT_PUBLIC_CAS_NETWORK=${network}`,
    '',
    '# ── Contracts ─────────────────────────────────────────────────────────────────',
    `NEXT_PUBLIC_AUTOMATION_MANAGER_ADDRESS=${state.automationManagerAddress}`,
    `NEXT_PUBLIC_WCFX_ADDRESS=${state.wcfxAddress}`,
    `NEXT_PUBLIC_CONFLUX_ESPACE_RPC=${state.rpcUrl}`,
    '',
  ];
  return lines.join('\n');
}

async function writeWithGuard(
  filePath: string,
  content: string,
  force: boolean,
): Promise<void> {
  if (existsSync(filePath) && !force) {
    const overwrite = await confirm({
      message: `${filePath} already exists. Overwrite?`,
      default: false,
    });
    if (!overwrite) {
      console.log(`  Skipped: ${filePath}`);
      return;
    }
  }
  writeFileSync(filePath, content, 'utf8');
  console.log(`  ✓ ${filePath} written`);
}

export async function writeEnv(state: WizardState): Promise<WizardState> {
  console.log('\n── Writing Env Files ─────────────────────────────────');

  const backendEnvPath = resolveFromCasRoot('apps/backend/.env');
  const frontendEnvPath = resolveFromCasRoot('apps/frontend/.env.local');

  const backendContent = generateBackendEnv(state);
  const frontendContent = generateFrontendEnv(state);

  await writeWithGuard(backendEnvPath, backendContent, state.force);
  await writeWithGuard(frontendEnvPath, frontendContent, state.force);

  return state;
}
