import fs from 'node:fs/promises';
import path from 'node:path';

import { findRepoRoot, getDocsSitePaths } from '../workspace.js';

const SKIP_PACKAGES = new Set([
  '@cfxdevkit/biome-config',
  '@cfxdevkit/tsconfig',
  '@cfxdevkit/moon-config',
  '@cfxdevkit/arch-rules',
  '@cfxdevkit/docs-site',
]);

const REPO_DIRS = [
  'repos/cfx-core',
  'repos/cfx-keys',
  'repos/cfx-ui',
  'repos/cfx-solidity',
  'repos/cfx-tools',
  'repos/cfx-domain',
] as const;

type CoverageSummaryTotal = {
  statements?: { pct?: number };
  branches?: { pct?: number };
  functions?: { pct?: number };
  lines?: { pct?: number };
};

type CoveragePackage = {
  name: string;
  rel: string;
  summary: { total?: CoverageSummaryTotal } | null;
};

function pct(value: number | undefined): string {
  if (value == null) return '—';
  return `${value.toFixed(2)} %`;
}

async function discoverCoveragePackages(repoRoot: string): Promise<CoveragePackage[]> {
  const result: CoveragePackage[] = [];
  for (const repoDir of REPO_DIRS) {
    for (const parent of ['packages', 'infra']) {
      const parentDir = path.join(repoRoot, repoDir, parent);
      let entries: string[];
      try {
        entries = await fs.readdir(parentDir);
      } catch {
        continue;
      }
      for (const entry of entries) {
        const pkgDir = path.join(parentDir, entry);
        let pkgJson: { name?: string; private?: boolean } | null = null;
        try {
          pkgJson = JSON.parse(await fs.readFile(path.join(pkgDir, 'package.json'), 'utf8')) as {
            name?: string;
            private?: boolean;
          };
        } catch {
          continue;
        }
        if (!pkgJson?.name || pkgJson.private === true) continue;
        if (SKIP_PACKAGES.has(pkgJson.name)) continue;

        let summary: { total?: CoverageSummaryTotal } | null = null;
        for (const location of [
          path.join(pkgDir, 'coverage', 'coverage-summary.json'),
          path.join(pkgDir, 'coverage-summary.json'),
        ]) {
          try {
            summary = JSON.parse(await fs.readFile(location, 'utf8')) as {
              total?: CoverageSummaryTotal;
            };
            break;
          } catch {
            // continue looking
          }
        }

        result.push({
          name: pkgJson.name,
          rel: `${repoDir}/${parent}/${entry}`,
          summary,
        });
      }
    }
  }
  return result;
}

function buildSummaryTable(packages: CoveragePackage[]): string | null {
  const covered = packages.filter((pkg) => pkg.summary?.total);
  if (covered.length === 0) return null;

  const rows = covered
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((pkg) => {
      const total = pkg.summary?.total;
      return `| \`${pkg.name}\` | ${pct(total?.statements?.pct)} | ${pct(total?.branches?.pct)} | ${pct(total?.functions?.pct)} | ${pct(total?.lines?.pct)} |`;
    });

  return `| Package | Statements | Branches | Functions | Lines |
|---|---|---|---|---|
${rows.join('\n')}`;
}

export async function syncCoveragePage(): Promise<{ withCoverage: number; total: number }> {
  const repoRoot = findRepoRoot();
  const { contentDir } = getDocsSitePaths(repoRoot);
  const dest = path.join(contentDir, 'coverage.mdx');
  const packages = await discoverCoveragePackages(repoRoot);

  const withCoverage = packages.filter((pkg) => pkg.summary?.total);
  const withoutCoverage = packages.filter((pkg) => !pkg.summary?.total);
  const summaryTable = buildSummaryTable(packages);
  const generatedAt = new Date().toISOString().split('T')[0] ?? '';
  const noCoverageList =
    withoutCoverage.length > 0
      ? withoutCoverage.map((pkg) => `- \`${pkg.name}\``).join('\n')
      : null;

  const mdx = `---
title: Test Coverage
description: Unit test coverage report for @cfxdevkit packages.
---

import { Callout, Tabs } from 'nextra/components'

# Test Coverage

Unit test coverage for packages in the \`@cfxdevkit\` monorepo.
Coverage is measured with [Vitest](https://vitest.dev/) and the **v8** provider.

Run coverage locally with:

\`\`\`bash
# Single package (example)
pnpm --filter @cfxdevkit/cdk test:coverage

# All packages
moon exec --force --quiet --no-actions --upstream none --downstream none :test -- --coverage
\`\`\`

<Callout type="info">
  This page is regenerated by \`pnpm sync:coverage\`. Run \`pnpm test:coverage\` per package first to update the data.
</Callout>

---

**Last updated:** ${generatedAt}
**Packages with coverage data:** ${withCoverage.length} / ${packages.length}

${
  summaryTable
    ? `## Summary\n\n${summaryTable}`
    : `<Callout type="warning">
  No coverage data found. Run \`pnpm --filter @cfxdevkit/cdk test:coverage\` then \`pnpm sync:coverage\` to populate this page.
</Callout>`
}

${
  noCoverageList
    ? `\n## Packages without coverage data\n\nThese packages have not had \`test:coverage\` run yet:\n\n${noCoverageList}\n`
    : ''
}`;

  await fs.writeFile(dest, mdx, 'utf8');
  console.log(
    `sync-coverage: wrote content/coverage.mdx (${withCoverage.length} packages with data, ${withoutCoverage.length} without)`,
  );
  return { withCoverage: withCoverage.length, total: packages.length };
}
