import type { TemplateFile } from './types.js';

export const PROJECT_EXAMPLE_SCRIPT_FILES: TemplateFile[] = [
  {
    path: 'scripts/deploy-contract.mjs',
    content: `#!/usr/bin/env node
/**
 * Deploy a compiled contract to Conflux eSpace.
 * Usage: node scripts/deploy-contract.mjs [contract-name]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const DEPLOYMENTS_FILE = resolve(import.meta.dirname, '../deployments/contracts.json');
const CONTRACT_NAME = process.argv[2] ?? 'Counter';
const NETWORK = process.env.NETWORK ?? 'local';

console.log(\`Deploying \${CONTRACT_NAME} to \${NETWORK}…\`);

// Load current deployments
const deployments = JSON.parse(readFileSync(DEPLOYMENTS_FILE, 'utf-8'));

// TODO: Replace with actual deployment using viem + @cfxdevkit/core
// Example:
//   const artifact = JSON.parse(readFileSync(\`./packages/contracts/artifacts/\${CONTRACT_NAME}.json\`));
//   const address = await deployContract(artifact.bytecode, artifact.abi, []);
const address = '0x0000000000000000000000000000000000000000'; // placeholder

deployments[NETWORK][CONTRACT_NAME] = address;
writeFileSync(DEPLOYMENTS_FILE, JSON.stringify(deployments, null, 2) + '\\n');
console.log(\`✓ \${CONTRACT_NAME} deployed at \${address}\`);
console.log(\`✓ Saved to deployments/contracts.json\`);
`,
  },
  {
    path: 'scripts/sync-project-network.mjs',
    content: `#!/usr/bin/env node
/**
 * Sync contract addresses from deployments/contracts.json into frontend env.
 * Usage: node scripts/sync-project-network.mjs [network]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const NETWORK = process.argv[2] ?? process.env.NETWORK ?? 'local';
const DEPLOYMENTS_FILE = resolve(import.meta.dirname, '../deployments/contracts.json');
const ENV_FILE = resolve(import.meta.dirname, '../packages/frontend/.env');

const deployments = JSON.parse(readFileSync(DEPLOYMENTS_FILE, 'utf-8'));
const networkDeployments = deployments[NETWORK] ?? {};

const envLines = Object.entries(networkDeployments)
  .map(([name, address]) => \`VITE_CONTRACT_\${name.toUpperCase()}=\${address}\`)
  .join('\\n');

writeFileSync(ENV_FILE, \`# Auto-generated by sync-project-network.mjs\\nVITE_NETWORK=\${NETWORK}\\n\${envLines}\\n\`);
console.log(\`✓ Synced \${Object.keys(networkDeployments).length} contract(s) for \${NETWORK} to \${ENV_FILE}\`);
`,
  },
  {
    path: 'scripts/doctor.mjs',
    content: `#!/usr/bin/env node
/**
 * Health-check script for the local development environment.
 * Usage: node scripts/doctor.mjs
 */
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

const checks = [
  {
    name: 'Node.js ≥ 20',
    pass: parseInt(process.versions.node.split('.')[0], 10) >= 20,
    fix: 'Install Node.js 20+ from https://nodejs.org',
  },
  {
    name: 'pnpm available',
    pass: await import('node:child_process')
      .then((m) => m.execSync('pnpm --version', { stdio: 'pipe' }))
      .then(() => true)
      .catch(() => false),
    fix: 'Run: npm install -g pnpm',
  },
  {
    name: 'deployments/contracts.json exists',
    pass: existsSync(resolve(import.meta.dirname, '../deployments/contracts.json')),
    fix: 'Run: node scripts/deploy-contract.mjs',
  },
  {
    name: 'frontend .env exists',
    pass: existsSync(resolve(import.meta.dirname, '../packages/frontend/.env')),
    fix: 'Run: node scripts/sync-project-network.mjs',
  },
];

let allPassed = true;
for (const check of checks) {
  const icon = check.pass ? '✓' : '✗';
  console.log(\`\${icon} \${check.name}\`);
  if (!check.pass) {
    console.log(\`  → Fix: \${check.fix}\`);
    allPassed = false;
  }
}

if (!allPassed) process.exit(1);
console.log('\\nAll checks passed!');
`,
  },
  {
    path: 'scripts/list-contracts.mjs',
    content: `#!/usr/bin/env node
/**
 * List all deployed contracts across networks.
 * Usage: node scripts/list-contracts.mjs [network]
 */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const DEPLOYMENTS_FILE = resolve(import.meta.dirname, '../deployments/contracts.json');
const NETWORK = process.argv[2];

const deployments = JSON.parse(readFileSync(DEPLOYMENTS_FILE, 'utf-8'));
const networks = NETWORK ? [NETWORK] : Object.keys(deployments);

for (const network of networks) {
  const contracts = deployments[network] ?? {};
  const count = Object.keys(contracts).length;
  console.log(\`\\n=== \${network} (\${count} contract\${count !== 1 ? 's' : ''}) ===\`);
  if (count === 0) {
    console.log('  (none)');
  } else {
    for (const [name, address] of Object.entries(contracts)) {
      console.log(\`  \${name}: \${address}\`);
    }
  }
}
`,
  },
  {
    path: 'dapp/wagmi.config.ts',
    content: `import { defineConfig } from '@wagmi/cli';
import { react } from '@wagmi/cli/plugins';

export default defineConfig({
  out: 'src/generated.ts',
  contracts: [
    // Add your contract ABIs here:
    // {
    //   name: 'Counter',
    //   abi: counterAbi,
    //   address: { 1030: '0x...', 71: '0x...' },
    // },
  ],
  plugins: [react()],
});
`,
  },
  {
    path: 'packages/frontend/src/components/ConnectButton.tsx',
    content: `// Re-export from @cfxdevkit/wallet-connect — replace with your own if needed
export { ConnectButton } from '@cfxdevkit/wallet-connect/ui';
`,
  },
  {
    path: 'packages/frontend/src/components/FaucetWidget.tsx',
    content: `import { FaucetWidget as BaseFaucetWidget } from '@cfxdevkit/defi-react/primitives';

interface Props {
  defaultAddress?: string;
}

export function FaucetWidget({ defaultAddress }: Props) {
  return (
    <BaseFaucetWidget
      defaultAddress={defaultAddress}
      onFund={async (address, amountWei) => {
        const res = await fetch('http://localhost:52000/accounts/fund', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ address, amount: amountWei }),
        });
        const data = await res.json() as { txHash: string };
        return { txHash: data.txHash };
      }}
    />
  );
}
`,
  },
];
