import type { ScriptRequirement } from './workspace.js';

export const rootToolingScriptRequirements: readonly ScriptRequirement[] = [
  {
    name: 'gen:api',
    expected: 'moon run arch-check:generate-api',
    severity: 'warning',
    description: 'deterministic API.md generator',
  },
  {
    name: 'gen:readme',
    expected: 'moon run arch-check:generate-readme',
    severity: 'warning',
    description: 'deterministic README.md generator',
  },
  {
    name: 'gen:structure',
    expected: 'moon run arch-check:generate-structure',
    severity: 'warning',
    description: 'deterministic STRUCTURE.md generator',
  },
  {
    name: 'tooling',
    expected: 'pnpm --filter @cfxdevkit/tooling-cli tooling --',
    severity: 'warning',
    description: 'canonical root tooling dispatcher',
  },
  {
    name: 'docs',
    expected: 'pnpm run tooling -- docs',
    severity: 'warning',
    description: 'docs namespace compatibility shim',
  },
  {
    name: 'docs:sync',
    expected: 'pnpm run tooling -- docs sync all',
    severity: 'warning',
    description: 'deterministic docs sync alias',
  },
  {
    name: 'docs:validate-wiki',
    expected: 'pnpm run tooling -- docs validate wiki',
    severity: 'warning',
    description: 'wiki validation alias',
  },
  {
    name: 'docs:validate-wiki-fix',
    expected: 'pnpm run tooling -- docs validate wiki-fix',
    severity: 'warning',
    description: 'wiki validation fix alias',
  },
  {
    name: 'docs:validate-packages',
    expected: 'pnpm run tooling -- docs validate content',
    severity: 'warning',
    description: 'generated package docs validation alias',
  },
  {
    name: 'sync:packages',
    expected: 'pnpm run tooling -- docs sync packages',
    severity: 'warning',
    description: 'package page sync alias',
  },
  {
    name: 'sync:architecture',
    expected: 'pnpm run tooling -- docs sync architecture',
    severity: 'warning',
    description: 'architecture page sync alias',
  },
  {
    name: 'sync:coverage',
    expected: 'pnpm run tooling -- docs sync coverage',
    severity: 'warning',
    description: 'coverage page sync alias',
  },
  {
    name: 'sync:wiki',
    expected: 'pnpm run tooling -- docs sync wiki',
    severity: 'warning',
    description: 'wiki sync alias',
  },
  {
    name: 'llm',
    expected: 'pnpm run tooling -- llm',
    severity: 'warning',
    description: 'llm namespace compatibility shim',
  },
  {
    name: 'llm:all',
    expected: 'pnpm run tooling -- llm all',
    severity: 'warning',
    description: 'llm all alias',
  },
  {
    name: 'llm:actions',
    expected: 'pnpm run tooling -- llm actions',
    severity: 'warning',
    description: 'llm actions alias',
  },
  {
    name: 'llm:action',
    expected: 'pnpm run tooling -- llm action',
    severity: 'warning',
    description: 'llm action alias',
  },
  {
    name: 'llm:ask',
    expected: 'pnpm run tooling -- llm ask',
    severity: 'warning',
    description: 'llm ask alias',
  },
  {
    name: 'llm:changeset',
    expected: 'pnpm run tooling -- llm changeset',
    severity: 'warning',
    description: 'llm changeset alias',
  },
  {
    name: 'llm:ci-cd',
    expected: 'pnpm run tooling -- llm ci-cd',
    severity: 'warning',
    description: 'llm ci-cd alias',
  },
  {
    name: 'llm:config',
    expected: 'pnpm run tooling -- llm config',
    severity: 'warning',
    description: 'llm config alias',
  },
  {
    name: 'llm:commit',
    expected: 'pnpm run tooling -- llm commit',
    severity: 'warning',
    description: 'llm commit alias',
  },
  {
    name: 'llm:docs-api',
    expected: 'pnpm run tooling -- llm docs-api',
    severity: 'warning',
    description: 'docs API enrichment alias',
  },
  {
    name: 'llm:readme-upkeep',
    expected: 'pnpm run tooling -- llm readme-upkeep',
    severity: 'warning',
    description: 'README enrichment alias',
  },
  {
    name: 'llm:package-pages',
    expected: 'pnpm run tooling -- llm package-pages',
    severity: 'warning',
    description: 'package page enrichment alias',
  },
  {
    name: 'llm:structure-upkeep',
    expected: 'pnpm run tooling -- llm structure-upkeep',
    severity: 'warning',
    description: 'STRUCTURE upkeep alias',
  },
  {
    name: 'llm:wiki',
    expected: 'pnpm run tooling -- docs wiki',
    severity: 'warning',
    description: 'wiki alias routed through docs namespace',
  },
  {
    name: 'llm:docs-pipeline',
    expected: 'pnpm run tooling -- llm docs-pipeline',
    severity: 'warning',
    description: 'docs pipeline review alias',
  },
  {
    name: 'llm:docs-upkeep',
    expected: 'pnpm run tooling -- llm docs-upkeep',
    severity: 'warning',
    description: 'docs content upkeep alias',
  },
  {
    name: 'llm:health',
    expected: 'pnpm run tooling -- llm health',
    severity: 'warning',
    description: 'provider health alias',
  },
  {
    name: 'llm:models',
    expected: 'pnpm run tooling -- llm models',
    severity: 'warning',
    description: 'model discovery alias',
  },
  {
    name: 'llm:release',
    expected: 'pnpm run tooling -- llm release',
    severity: 'warning',
    description: 'release helper alias',
  },
  {
    name: 'llm:review',
    expected: 'pnpm run tooling -- llm review',
    severity: 'warning',
    description: 'review alias',
  },
  {
    name: 'llm:test-audit',
    expected: 'pnpm run tooling -- llm test-audit',
    severity: 'warning',
    description: 'test audit alias',
  },
  {
    name: 'llm:test-upkeep',
    expected: 'pnpm run tooling -- llm test-upkeep',
    severity: 'warning',
    description: 'test upkeep alias',
  },
  {
    name: 'llm:validation',
    expected: 'pnpm run tooling -- llm validation',
    severity: 'warning',
    description: 'validation alias',
  },
];
