$schema: 'https://moonrepo.dev/schemas/project.json'

layer: 'library'
language: 'typescript'

dependsOn:
  - 'cdk-repo-check'
  - 'docs-pipeline'

fileGroups:
  sources:
    - 'src/**/*'
    - 'workers/**/*'
    - 'package.json'
    - 'tsconfig*.json'