// biome-ignore lint: Nextra requires default export for meta files
export default {
  index: 'Overview',
  abis: '@cfxdevkit/abis',
  automation: '@cfxdevkit/automation',
  cdk: '@cfxdevkit/cdk',
  cli: '@cfxdevkit/cli',
  client: '@cfxdevkit/client',
  compiler: '@cfxdevkit/compiler',
  contracts: '@cfxdevkit/contracts',
  create: '@cfxdevkit/create',
  'defi-react': '@cfxdevkit/defi-react',
  devnode: '@cfxdevkit/devnode',
  'devnode-server': '@cfxdevkit/devnode-server',
  executor: '@cfxdevkit/executor',
  'game-engine': '@cfxdevkit/game-engine',
  'keystore-server': '@cfxdevkit/keystore-server',
  'llm-agents': '@cfxdevkit/llm-agents',
  'llm-tools': '@cfxdevkit/llm-tools',
  'mcp-server': '@cfxdevkit/mcp-server',
  protocol: '@cfxdevkit/protocol',
  react: '@cfxdevkit/react',
  services: '@cfxdevkit/services',
  testing: '@cfxdevkit/testing',
  theme: '@cfxdevkit/theme',
  ui: '@cfxdevkit/ui',
  'ui-core': '@cfxdevkit/ui-core',
  wallet: '@cfxdevkit/wallet',
  'wallet-connect': '@cfxdevkit/wallet-connect',
};
